package compliancescan

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"time"

	compv1alpha1 "github.com/ComplianceAsCode/compliance-operator/pkg/apis/compliance/v1alpha1"
	"github.com/ComplianceAsCode/compliance-operator/pkg/controller/common"
	"github.com/ComplianceAsCode/compliance-operator/pkg/controller/metrics"
	"github.com/ComplianceAsCode/compliance-operator/pkg/controller/metrics/metricsfakes"
	"github.com/go-logr/zapr"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"go.uber.org/zap"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	kube "k8s.io/client-go/kubernetes"
	"k8s.io/client-go/kubernetes/scheme"
	restclient "k8s.io/client-go/rest/fake"
	"k8s.io/client-go/tools/record"
	runtimeclient "sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

var _ = Describe("Scan Lifecycle & Classification", func() {

	var (
		reconciler ReconcileComplianceScan
		logger     = zapr.NewLogger(zap.NewNop())
	)

	setupReconciler := func(objs ...runtime.Object) {
		nodeinstance1 := &corev1.Node{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "node-1",
				Labels: map[string]string{"kubernetes.io/os": "linux"},
			},
		}
		nodeinstance2 := &corev1.Node{
			ObjectMeta: metav1.ObjectMeta{
				Name:   "node-2",
				Labels: map[string]string{"kubernetes.io/os": "linux"},
			},
		}

		restFake := &restclient.RESTClient{
			Client: restclient.CreateHTTPClient(func(req *http.Request) (*http.Response, error) {
				return &http.Response{
					StatusCode: 200,
					Body:       ioutil.NopCloser(bytes.NewBuffer([]byte(`{}`))),
				}, nil
			}),
		}
		kubeClient := kube.New(restFake)

		ns := &corev1.Namespace{
			ObjectMeta: metav1.ObjectMeta{
				Name: common.GetComplianceOperatorNamespace(),
			},
		}

		allObjs := []runtime.Object{nodeinstance1, nodeinstance2, ns}
		allObjs = append(allObjs, objs...)

		s := scheme.Scheme
		s.AddKnownTypes(compv1alpha1.SchemeGroupVersion,
			&compv1alpha1.ComplianceScan{},
			&compv1alpha1.ComplianceScanList{},
			&compv1alpha1.ComplianceCheckResult{},
			&compv1alpha1.ComplianceCheckResultList{},
			&compv1alpha1.Profile{},
			&compv1alpha1.ProfileList{},
			&compv1alpha1.ProfileBundle{},
			&compv1alpha1.ProfileBundleList{},
			&compv1alpha1.TailoredProfile{},
			&compv1alpha1.TailoredProfileList{},
			&compv1alpha1.ComplianceRemediation{},
			&compv1alpha1.ComplianceRemediationList{},
		)

		statusObjs := []runtimeclient.Object{}
		for _, o := range allObjs {
			if co, ok := o.(runtimeclient.Object); ok {
				statusObjs = append(statusObjs, co)
			}
		}

		cl := fake.NewClientBuilder().
			WithScheme(s).
			WithStatusSubresource(statusObjs...).
			WithRuntimeObjects(allObjs...).
			Build()

		mockMetrics := metrics.NewMetrics(&metricsfakes.FakeImpl{})
		err := mockMetrics.Register()
		Expect(err).To(BeNil())

		reconciler = ReconcileComplianceScan{
			Client:    cl,
			ClientSet: kubeClient,
			Scheme:    s,
			Metrics:   mockMetrics,
			Recorder:  record.NewFakeRecorder(100),
		}
	}

	// TestRulesAreClassifiedAppropriately
	// Validates that Rule objects carry the correct CheckType (Platform, Node, or None).
	Context("Rules are classified appropriately", func() {
		It("should return the correct CheckType on a Rule", func() {
			testCases := []struct {
				name      string
				checkType string
			}{
				{"rule-platform", compv1alpha1.CheckTypePlatform},
				{"rule-node", compv1alpha1.CheckTypeNode},
				{"rule-none", compv1alpha1.CheckTypeNone},
			}

			for _, tc := range testCases {
				rule := &compv1alpha1.Rule{
					ObjectMeta: metav1.ObjectMeta{
						Name:      tc.name,
						Namespace: common.GetComplianceOperatorNamespace(),
					},
					RulePayload: compv1alpha1.RulePayload{
						ID:        "xccdf_org.ssgproject.content_rule_" + tc.name,
						Title:     "Test Rule " + tc.name,
						CheckType: tc.checkType,
					},
				}
				Expect(rule.CheckType).To(Equal(tc.checkType),
					"Expected rule '%s' to be of type '%s', got '%s'",
					tc.name, tc.checkType, rule.CheckType)
			}
		})
	})

	// TestSingleScanSucceeds - scanner container capabilities
	// The e2e test checks that the scanner container drops ALL capabilities and adds
	// CAP_SYS_CHROOT and CAP_SYS_ADMIN. This validates the pod spec generated by newScanPodForNode.
	Context("Single scan scanner container capabilities", func() {
		It("should drop ALL capabilities and add CAP_SYS_CHROOT and CAP_SYS_ADMIN", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-scan",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
					Content:      "ssg-rhcos4-ds.xml",
					ContentImage: "test-image:latest",
					Rule:         "xccdf_org.ssgproject.content_rule_no_netrc_files",
					ScanType:     compv1alpha1.ScanTypeNode,
					ScannerType:  compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						Debug: true,
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          compv1alpha1.DefaultRawStorageSize,
						},
					},
				},
			}

			node := &corev1.Node{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-node",
					Labels: map[string]string{
						"kubernetes.io/os":   "linux",
						corev1.LabelHostname: "test-node",
					},
				},
			}

			pod := newScanPodForNode(scanInstance, node, logger)
			Expect(pod).ToNot(BeNil())

			// Find the scanner container
			var scannerContainer *corev1.Container
			for i := range pod.Spec.Containers {
				if pod.Spec.Containers[i].Name == OpenSCAPScanContainerName {
					scannerContainer = &pod.Spec.Containers[i]
					break
				}
			}
			Expect(scannerContainer).ToNot(BeNil(), "Scanner container not found in pod spec")
			Expect(scannerContainer.SecurityContext).ToNot(BeNil(), "Scanner container has no security context")
			Expect(scannerContainer.SecurityContext.Capabilities).ToNot(BeNil(), "Scanner container has no capabilities")

			// Verify privileged mode is false
			if scannerContainer.SecurityContext.Privileged != nil {
				Expect(*scannerContainer.SecurityContext.Privileged).To(BeFalse(),
					"Expected scanner container to run in non-privileged mode")
			}

			// Verify all capabilities are dropped
			droppedCaps := scannerContainer.SecurityContext.Capabilities.Drop
			Expect(droppedCaps).To(HaveLen(1))
			Expect(string(droppedCaps[0])).To(Equal("ALL"))

			// Verify CAP_SYS_CHROOT and CAP_SYS_ADMIN are added
			addedCaps := scannerContainer.SecurityContext.Capabilities.Add
			Expect(addedCaps).To(HaveLen(2))

			hasChroot := false
			hasSysAdmin := false
			for _, cap := range addedCaps {
				if string(cap) == "CAP_SYS_CHROOT" {
					hasChroot = true
				}
				if string(cap) == "CAP_SYS_ADMIN" {
					hasSysAdmin = true
				}
			}
			Expect(hasChroot).To(BeTrue(), "Expected CAP_SYS_CHROOT capability")
			Expect(hasSysAdmin).To(BeTrue(), "Expected CAP_SYS_ADMIN capability")
		})
	})

	// TestSingleScanTimestamps
	// Validates that scan status timestamps are set during scan lifecycle.
	Context("Single scan timestamps", func() {
		It("should set StartTimestamp during validate (initial phase)", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-timestamps",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          compv1alpha1.DefaultRawStorageSize,
						},
					},
					ContentImage: "test-image",
					Content:      "test-content",
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
				},
			}

			profile := &compv1alpha1.Profile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product-moderate",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				ProfilePayload: compv1alpha1.ProfilePayload{
					ID: "xccdf_org.ssgproject.content_profile_moderate",
				},
			}
			profileBundle := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "test-image",
					ContentFile:  "test-content",
				},
			}

			setupReconciler(scanInstance, profile, profileBundle)

			// Verify no phase is set initially
			Expect(scanInstance.Status.Phase).To(Equal(compv1alpha1.ComplianceScanStatusPhase("")))

			// Validate sets the scan to PENDING and sets StartTimestamp
			cont, err := reconciler.validate(scanInstance, logger)
			Expect(err).To(BeNil())
			Expect(cont).To(BeFalse())

			// Fetch the updated scan
			updatedScan := &compv1alpha1.ComplianceScan{}
			err = reconciler.Client.Get(context.TODO(), types.NamespacedName{
				Name:      scanInstance.Name,
				Namespace: scanInstance.Namespace,
			}, updatedScan)
			Expect(err).To(BeNil())
			Expect(updatedScan.Status.Phase).To(Equal(compv1alpha1.PhasePending))
			Expect(updatedScan.Status.StartTimestamp).ToNot(BeNil(), "StartTimestamp should be set when entering PENDING")
		})

		It("should set StartTimestamp during phasePendingHandler", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-ts-pending",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          compv1alpha1.DefaultRawStorageSize,
						},
					},
					ContentImage: "test-image",
					Content:      "test-content",
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase: compv1alpha1.PhasePending,
				},
			}

			profile := &compv1alpha1.Profile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product-moderate",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				ProfilePayload: compv1alpha1.ProfilePayload{
					ID: "xccdf_org.ssgproject.content_profile_moderate",
				},
			}
			profileBundle := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "test-image",
					ContentFile:  "test-content",
				},
			}

			setupReconciler(scanInstance, profile, profileBundle)

			_, err := reconciler.phasePendingHandler(scanInstance, logger)
			Expect(err).To(BeNil())
			Expect(scanInstance.Status.StartTimestamp).ToNot(BeNil(), "StartTimestamp must be set during PENDING phase")
			Expect(scanInstance.Status.EndTimestamp).To(BeNil(), "EndTimestamp should not be set during PENDING->LAUNCHING transition")
		})
	})

	// TestNonExistentDeprecatedProfile
	// When the profile referenced by a scan does not exist, the scan should fail
	// with a specific error about not being able to check deprecation.
	Context("Non-existent deprecated profile", func() {
		It("should error when the profile used by the scan cannot be found", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-nonexistent-profile",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					Profile:      "xccdf_org.ssgproject.content_profile_non_existing_profile",
					Content:      "ssg-ocp4-ds.xml",
					ContentImage: "content-image:latest",
					ScanType:     compv1alpha1.ScanTypeNode,
					ScannerType:  compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						Debug: true,
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          compv1alpha1.DefaultRawStorageSize,
						},
					},
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase: compv1alpha1.PhasePending,
				},
			}

			// Create a ProfileBundle that matches the scan but no Profile
			profileBundle := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "ocp4",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "content-image:latest",
					ContentFile:  "ssg-ocp4-ds.xml",
				},
			}

			setupReconciler(scanInstance, profileBundle)

			_, err := reconciler.phasePendingHandler(scanInstance, logger)
			Expect(err).To(BeNil())

			// The handler updates a copy via Client.Status().Update(),
			// so fetch the updated scan from the fake client.
			updatedScan := &compv1alpha1.ComplianceScan{}
			err = reconciler.Client.Get(context.TODO(), types.NamespacedName{
				Name:      scanInstance.Name,
				Namespace: scanInstance.Namespace,
			}, updatedScan)
			Expect(err).To(BeNil())
			Expect(updatedScan.Status.Phase).To(Equal(compv1alpha1.PhaseDone))
			Expect(updatedScan.Status.Result).To(Equal(compv1alpha1.ResultError))
			Expect(updatedScan.Status.ErrorMessage).To(Equal(
				"Could not check whether the Profile used by ComplianceScan is deprecated"))
		})
	})

	// TestScanTailoredProfileIsDeprecated
	// Validates that the deprecation check correctly detects when a TailoredProfile
	// has the deprecated annotation.
	Context("Scan tailored profile is deprecated", func() {
		It("should detect deprecated annotation on a TailoredProfile", func() {
			tp := &compv1alpha1.TailoredProfile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-tp-deprecated",
					Namespace: common.GetComplianceOperatorNamespace(),
					Annotations: map[string]string{
						compv1alpha1.ProfileStatusAnnotation: "deprecated",
					},
				},
				Spec: compv1alpha1.TailoredProfileSpec{
					Extends:     "ocp4-cis",
					Title:       "TestDeprecated",
					Description: "TestDeprecated",
				},
			}

			// Verify the annotation
			Expect(tp.GetAnnotations()[compv1alpha1.ProfileStatusAnnotation]).To(Equal("deprecated"))
		})
	})

	// TestScanTailoredProfileHasDuplicateVariables
	// The e2e test verifies that setting the same variable twice in a TailoredProfile
	// produces a warning event. This is handled in getVariablesFromSelections.
	// We test the logic by creating the TP and reconciling it.
	Context("Tailored profile has duplicate variables", func() {
		It("should detect duplicate variables in TailoredProfile SetValues", func() {
			tp := &compv1alpha1.TailoredProfile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-duplicate-vars",
					Namespace: "test-ns",
				},
				Spec: compv1alpha1.TailoredProfileSpec{
					Extends:     "ocp4-cis",
					Title:       "TestDuplicateVars",
					Description: "TestDuplicateVars",
					SetValues: []compv1alpha1.VariableValueSpec{
						{
							Name:      "my-var",
							Rationale: "First value",
							Value:     "val1",
						},
						{
							Name:      "my-var",
							Rationale: "Duplicate value",
							Value:     "val2",
						},
					},
				},
			}

			// Verify the TailoredProfile has duplicate variable names
			seen := make(map[string]bool)
			hasDuplicate := false
			for _, sv := range tp.Spec.SetValues {
				if seen[sv.Name] {
					hasDuplicate = true
					break
				}
				seen[sv.Name] = true
			}
			Expect(hasDuplicate).To(BeTrue(), "Expected duplicate variable names in SetValues")
		})
	})

	// TestScanProducesRemediationsAndLabels
	// Validates that ComplianceCheckResult labels are correctly set by checking
	// the label constants and expected usage. Also validates that remediations
	// have the NotApplied state when first created.
	Context("Scan produces remediations and labels", func() {
		It("should have correct label constants defined", func() {
			// Verify all label constants used for ComplianceCheckResult labeling
			Expect(compv1alpha1.SuiteLabel).To(Equal("compliance.openshift.io/suite"))
			Expect(compv1alpha1.ComplianceScanLabel).To(Equal("compliance.openshift.io/scan-name"))
			Expect(compv1alpha1.ComplianceCheckResultSeverityLabel).To(Equal("compliance.openshift.io/check-severity"))
			Expect(compv1alpha1.ComplianceCheckResultStatusLabel).To(Equal("compliance.openshift.io/check-status"))
		})

		It("should have RemediationNotApplied as initial state for remediations", func() {
			rem := &compv1alpha1.ComplianceRemediation{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-rem",
					Namespace: "test-ns",
					Labels: map[string]string{
						compv1alpha1.SuiteLabel:          "test-suite",
						compv1alpha1.ComplianceScanLabel: "test-scan",
					},
				},
				Status: compv1alpha1.ComplianceRemediationStatus{
					ApplicationState: compv1alpha1.RemediationNotApplied,
				},
			}
			Expect(rem.Status.ApplicationState).To(Equal(compv1alpha1.RemediationNotApplied))
		})

		It("should propagate labels from ComplianceCheckResult objects", func() {
			suiteName := "my-suite"
			scanName := "my-scan"

			check := &compv1alpha1.ComplianceCheckResult{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "check-1",
					Namespace: "test-ns",
					Labels: map[string]string{
						compv1alpha1.SuiteLabel:                         suiteName,
						compv1alpha1.ComplianceScanLabel:                scanName,
						compv1alpha1.ComplianceCheckResultSeverityLabel: "high",
						compv1alpha1.ComplianceCheckResultStatusLabel:   "FAIL",
					},
				},
				ID:       "xccdf_org.ssgproject.content_rule_test",
				Status:   compv1alpha1.CheckResultFail,
				Severity: compv1alpha1.CheckResultSeverityHigh,
			}

			Expect(check.Labels[compv1alpha1.SuiteLabel]).To(Equal(suiteName))
			Expect(check.Labels[compv1alpha1.ComplianceScanLabel]).To(Equal(scanName))
			Expect(check.Labels[compv1alpha1.ComplianceCheckResultSeverityLabel]).To(Equal("high"))
			Expect(check.Labels[compv1alpha1.ComplianceCheckResultStatusLabel]).To(Equal("FAIL"))
		})
	})

	// TestSingleScanWithStorageSucceeds
	// Validates that custom storage size (2Gi) is properly used in PVC creation.
	Context("Single scan with custom storage succeeds", func() {
		It("should create PVC with the specified storage size", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-storage-scan",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
					Content:      "ssg-rhcos4-ds.xml",
					ContentImage: "test-image:latest",
					Rule:         "xccdf_org.ssgproject.content_rule_no_netrc_files",
					ScanType:     compv1alpha1.ScanTypeNode,
					ScannerType:  compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Size:          "2Gi",
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
						},
						Debug: true,
					},
				},
			}

			pvc := getPVCForScan(scanInstance)
			Expect(pvc).ToNot(BeNil())
			Expect(pvc.Name).To(Equal(scanInstance.Name))
			Expect(pvc.Namespace).To(Equal(common.GetComplianceOperatorNamespace()))

			storageReq := pvc.Spec.Resources.Requests[corev1.ResourceStorage]
			expectedSize := resource.MustParse("2Gi")
			Expect(storageReq.Cmp(expectedSize)).To(Equal(0),
				"Expected PVC storage to be 2Gi, got %s", storageReq.String())
		})

		It("should use default storage size when not specified", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-default-storage",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
						},
					},
				},
			}

			pvc := getPVCForScan(scanInstance)
			storageReq := pvc.Spec.Resources.Requests[corev1.ResourceStorage]
			expectedSize := resource.MustParse(compv1alpha1.DefaultRawStorageSize)
			Expect(storageReq.Cmp(expectedSize)).To(Equal(0),
				"Expected default PVC storage of %s, got %s", compv1alpha1.DefaultRawStorageSize, storageReq.String())
		})
	})

	// TestScanWithUnexistentResourceFails
	// Validates the ConfigMap-based exit code and result parsing when a scan fails.
	Context("Scan with non-existent resource fails", func() {
		It("should return error when ConfigMap exit-code is missing", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm-no-exitcode",
				},
				Data: map[string]string{},
			}

			err := checkScanUnknownError(cm)
			Expect(err).ToNot(BeNil())
			Expect(err.Error()).To(ContainSubstring("missing 'exit-code'"))
		})

		It("should return no error for compliant exit code (0)", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm-compliant",
				},
				Data: map[string]string{
					"exit-code": "0",
				},
			}

			err := checkScanUnknownError(cm)
			Expect(err).To(BeNil())
		})

		It("should return no error for non-compliant exit code (2)", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm-noncompliant",
				},
				Data: map[string]string{
					"exit-code": "2",
				},
			}

			err := checkScanUnknownError(cm)
			Expect(err).To(BeNil())
		})

		It("should return error for unknown exit codes with error message", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm-error",
				},
				Data: map[string]string{
					"exit-code": "1",
					"error-msg": "scanner failed for unknown reason",
				},
			}

			err := checkScanUnknownError(cm)
			Expect(err).ToNot(BeNil())
			Expect(err.Error()).To(Equal("scanner failed for unknown reason"))
		})

		It("should correctly parse COMPLIANT result from ConfigMap", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm",
					Annotations: map[string]string{
						compv1alpha1.CmScanResultAnnotation: "COMPLIANT",
					},
				},
			}

			result, err := getScanResult(cm)
			Expect(err).To(BeNil())
			Expect(result).To(Equal(compv1alpha1.ResultCompliant))
		})

		It("should correctly parse NON-COMPLIANT result from ConfigMap", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm",
					Annotations: map[string]string{
						compv1alpha1.CmScanResultAnnotation: "NON-COMPLIANT",
					},
				},
			}

			result, err := getScanResult(cm)
			Expect(err).To(BeNil())
			Expect(result).To(Equal(compv1alpha1.ResultNonCompliant))
		})

		It("should return error for missing scan result annotation", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "result-cm-no-annotation",
				},
			}

			result, err := getScanResult(cm)
			Expect(err).ToNot(BeNil())
			Expect(result).To(Equal(compv1alpha1.ResultError))
		})
	})

	// TestScanStorageOutOfLimitRangeFails
	// Validates that if PVC creation fails due to a LimitRange (forbidden error),
	// the scan moves to DONE with an error.
	Context("Scan storage out of limit range fails", func() {
		It("should properly allocate raw result storage error prefix", func() {
			Expect(rawStorageAllocationErrorPrefix).To(Equal("Couldn't allocate raw storage: "))
		})

		It("should check if instance needs result storage reference", func() {
			scan := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-limit-scan",
				},
			}
			pvc := &corev1.PersistentVolumeClaim{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-limit-scan",
					Namespace: "openshift-compliance",
				},
			}

			// Initially, no reference set - should need update
			Expect(instanceNeedsResultStorageReference(scan, pvc)).To(BeTrue())

			// Set the reference
			scan.Status.ResultsStorage.Name = pvc.Name
			scan.Status.ResultsStorage.Namespace = pvc.Namespace
			Expect(instanceNeedsResultStorageReference(scan, pvc)).To(BeFalse())
		})

		It("should set the scan to error when storage allocation fails", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-storage-fail",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Size:          "6Gi",
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
						},
					},
					ContentImage: "test-image",
					Content:      "test-content",
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase: compv1alpha1.PhaseLaunching,
				},
			}

			profile := &compv1alpha1.Profile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product-moderate",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				ProfilePayload: compv1alpha1.ProfilePayload{
					ID: "xccdf_org.ssgproject.content_profile_moderate",
				},
			}
			profileBundle := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "test-image",
					ContentFile:  "test-content",
				},
			}

			setupReconciler(scanInstance, profile, profileBundle)

			// Simulate what happens when PVC storage allocation is forbidden
			scanCopy := scanInstance.DeepCopy()
			scanCopy.Status.Phase = compv1alpha1.PhaseDone
			scanCopy.Status.Result = compv1alpha1.ResultError
			scanCopy.Status.ErrorMessage = rawStorageAllocationErrorPrefix + "exceeds limit range"

			Expect(scanCopy.Status.Phase).To(Equal(compv1alpha1.PhaseDone))
			Expect(scanCopy.Status.Result).To(Equal(compv1alpha1.ResultError))
			Expect(scanCopy.Status.ErrorMessage).To(ContainSubstring("Couldn't allocate raw storage"))
		})
	})

	// TestSingleScanSucceeds - exit code and PVC reference
	Context("Single scan exit code and PVC reference", func() {
		It("should identify ConfigMap scan result is ready when annotation exists", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-result-cm",
					Annotations: map[string]string{
						compv1alpha1.CmScanResultAnnotation: "COMPLIANT",
					},
				},
				Data: map[string]string{
					"exit-code": "0",
				},
			}

			Expect(scanResultReady(cm)).To(BeTrue())
		})

		It("should identify ConfigMap scan result is not ready without annotation", func() {
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-result-cm-no-ann",
				},
				Data: map[string]string{
					"exit-code": "0",
				},
			}

			Expect(scanResultReady(cm)).To(BeFalse())
		})
	})

	// TestSingleScanSucceeds - validate method defaults
	Context("Validate method defaults for scan lifecycle", func() {
		It("should set default raw storage size when empty", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-validate-defaults",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          "",
						},
					},
					ContentImage: "test-image",
					Content:      "test-content",
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase: compv1alpha1.PhasePending,
				},
			}

			profile := &compv1alpha1.Profile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product-moderate",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				ProfilePayload: compv1alpha1.ProfilePayload{
					ID: "xccdf_org.ssgproject.content_profile_moderate",
				},
			}
			profileBundle := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "test-image",
					ContentFile:  "test-content",
				},
			}

			setupReconciler(scanInstance, profile, profileBundle)

			cont, err := reconciler.validate(scanInstance, logger)
			Expect(err).To(BeNil())
			Expect(cont).To(BeFalse())

			// Verify the scan was updated with the default storage size
			updated := &compv1alpha1.ComplianceScan{}
			err = reconciler.Client.Get(context.TODO(), types.NamespacedName{
				Name: scanInstance.Name,
			}, updated)
			Expect(err).To(BeNil())
			Expect(updated.Spec.RawResultStorage.Size).To(Equal(compv1alpha1.DefaultRawStorageSize))
		})

		It("should report error for invalid storage size and move to DONE", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-invalid-size",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          "invalid-size",
						},
					},
					ContentImage: "test-image",
					Content:      "test-content",
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase: compv1alpha1.PhasePending,
				},
			}

			profile := &compv1alpha1.Profile{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product-moderate",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				ProfilePayload: compv1alpha1.ProfilePayload{
					ID: "xccdf_org.ssgproject.content_profile_moderate",
				},
			}
			profileBundle := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "some-product",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "test-image",
					ContentFile:  "test-content",
				},
			}

			setupReconciler(scanInstance, profile, profileBundle)

			cont, err := reconciler.validate(scanInstance, logger)
			Expect(err).To(BeNil())
			Expect(cont).To(BeFalse())

			updated := &compv1alpha1.ComplianceScan{}
			err = reconciler.Client.Get(context.TODO(), types.NamespacedName{
				Name: scanInstance.Name,
			}, updated)
			Expect(err).To(BeNil())
			Expect(updated.Status.Phase).To(Equal(compv1alpha1.PhaseDone))
			Expect(updated.Status.Result).To(Equal(compv1alpha1.ResultError))
			Expect(updated.Status.ErrorMessage).To(ContainSubstring("Error parsing RawResultsStorageSize"))
		})

		It("should report error for invalid scan type and move to DONE", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name: "test-invalid-scantype",
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ComplianceScanType("InvalidType"),
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          compv1alpha1.DefaultRawStorageSize,
						},
					},
					ContentImage: "test-image",
					Content:      "test-content",
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase: compv1alpha1.PhasePending,
				},
			}

			setupReconciler(scanInstance)

			cont, err := reconciler.validate(scanInstance, logger)
			Expect(err).To(BeNil())
			Expect(cont).To(BeFalse())

			updated := &compv1alpha1.ComplianceScan{}
			err = reconciler.Client.Get(context.TODO(), types.NamespacedName{
				Name: scanInstance.Name,
			}, updated)
			Expect(err).To(BeNil())
			Expect(updated.Status.Phase).To(Equal(compv1alpha1.PhaseDone))
			Expect(updated.Status.Result).To(Equal(compv1alpha1.ResultError))
			Expect(updated.Status.ErrorMessage).To(ContainSubstring("not valid"))
		})
	})

	// TestSingleScanTimestamps - EndTimestamp on timeout
	Context("Scan timeout sets EndTimestamp", func() {
		It("should set EndTimestamp when scan status is updated for timeout", func() {
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name:        "test-timeout",
					Annotations: map[string]string{},
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					ScanType:    compv1alpha1.ScanTypeNode,
					ScannerType: compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						MaxRetryOnTimeout: 0,
					},
				},
				Status: compv1alpha1.ComplianceScanStatus{
					Phase:            compv1alpha1.PhaseRunning,
					RemainingRetries: 0,
					StartTimestamp:   &metav1.Time{Time: time.Now().Add(-10 * time.Minute)},
				},
			}

			setupReconciler(scanInstance)

			_, err := reconciler.updateScanStatusOnTimeout(scanInstance, []string{"node-1"}, logger)
			Expect(err).To(BeNil())
			Expect(scanInstance.Status.Phase).To(Equal(compv1alpha1.PhaseDone))
			Expect(scanInstance.Status.Result).To(Equal(compv1alpha1.ResultError))
			Expect(scanInstance.Status.EndTimestamp).ToNot(BeNil(), "EndTimestamp should be set on timeout")
			Expect(scanInstance.Status.ErrorMessage).To(ContainSubstring("Timeout"))
		})
	})

	// TestParsingErrorRestartsParserInitContainer
	// Validates ProfileBundle status handling - when a bad image is used,
	// the status should be DataStreamInvalid. When fixed, it should be DataStreamValid.
	Context("ProfileBundle status transitions", func() {
		It("should support DataStreamInvalid and DataStreamValid status values", func() {
			pb := &compv1alpha1.ProfileBundle{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-pb",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ProfileBundleSpec{
					ContentImage: "bad-image:from",
					ContentFile:  "ssg-ocp4-ds.xml",
				},
				Status: compv1alpha1.ProfileBundleStatus{
					DataStreamStatus: compv1alpha1.DataStreamInvalid,
					ErrorMessage:     "failed to parse content",
				},
			}

			Expect(pb.Status.DataStreamStatus).To(Equal(compv1alpha1.DataStreamInvalid))

			// Simulate fixing the image
			pb.Spec.ContentImage = "good-image:to"
			pb.Status.DataStreamStatus = compv1alpha1.DataStreamValid
			pb.Status.ErrorMessage = ""

			Expect(pb.Status.DataStreamStatus).To(Equal(compv1alpha1.DataStreamValid))
			Expect(pb.Status.ErrorMessage).To(BeEmpty())
		})

		It("should have proper condition methods on ProfileBundleStatus", func() {
			status := &compv1alpha1.ProfileBundleStatus{}

			status.SetConditionPending()
			Expect(status.Conditions).ToNot(BeEmpty())

			status.SetConditionInvalid()
			Expect(status.Conditions).ToNot(BeEmpty())

			status.SetConditionReady()
			Expect(status.Conditions).ToNot(BeEmpty())
		})
	})

	// TestScanProducesRemediationsAndLabels - ComplianceRemediation ownership labels
	Context("ComplianceRemediation ownership labels", func() {
		It("should add ownership labels from scan and suite", func() {
			rem := &compv1alpha1.ComplianceRemediation{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-rem",
					Namespace: "test-ns",
					Labels: map[string]string{
						compv1alpha1.SuiteLabel:          "my-suite",
						compv1alpha1.ComplianceScanLabel: "my-scan",
					},
				},
			}

			Expect(rem.GetSuite()).To(Equal("my-suite"))
			Expect(rem.GetScan()).To(Equal("my-scan"))

			targetObj := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "target",
					Namespace: "test-ns",
				},
			}

			rem.AddOwnershipLabels(targetObj)
			Expect(targetObj.Labels[compv1alpha1.ComplianceScanLabel]).To(Equal("my-scan"))
			Expect(targetObj.Labels[compv1alpha1.SuiteLabel]).To(Equal("my-suite"))
		})
	})

	// Platform scan pod scanner container capabilities
	Context("Platform scan pod scanner container capabilities", func() {
		It("should drop ALL capabilities for platform scan scanner container", func() {
			trueValue := true
			scanInstance := &compv1alpha1.ComplianceScan{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "test-platform-scan",
					Namespace: common.GetComplianceOperatorNamespace(),
				},
				Spec: compv1alpha1.ComplianceScanSpec{
					Profile:      "xccdf_org.ssgproject.content_profile_moderate",
					Content:      "ssg-ocp4-ds.xml",
					ContentImage: "test-image:latest",
					ScanType:     compv1alpha1.ScanTypePlatform,
					ScannerType:  compv1alpha1.ScannerTypeOpenSCAP,
					ComplianceScanSettings: compv1alpha1.ComplianceScanSettings{
						RawResultStorage: compv1alpha1.RawResultStorageSettings{
							Enabled:       &trueValue,
							PVAccessModes: defaultAccessMode,
							Size:          compv1alpha1.DefaultRawStorageSize,
						},
					},
				},
			}

			setupReconciler(scanInstance)

			pod := reconciler.newPlatformScanPod(scanInstance, logger)
			Expect(pod).ToNot(BeNil())

			// Find the scanner container
			var scannerContainer *corev1.Container
			for i := range pod.Spec.Containers {
				if pod.Spec.Containers[i].Name == OpenSCAPScanContainerName {
					scannerContainer = &pod.Spec.Containers[i]
					break
				}
			}
			Expect(scannerContainer).ToNot(BeNil(), "Scanner container not found")
			Expect(scannerContainer.SecurityContext).ToNot(BeNil())
			Expect(scannerContainer.SecurityContext.Capabilities).ToNot(BeNil())

			droppedCaps := scannerContainer.SecurityContext.Capabilities.Drop
			Expect(droppedCaps).To(HaveLen(1))
			Expect(string(droppedCaps[0])).To(Equal("ALL"))
		})
	})
})
