FROM registry.redhat.io/ubi9/ubi-minimal:latest

LABEL \
        io.k8s.display-name="OpenSCAP scanner for compliance-operator" \
        io.k8s.description="An OpenSCAP operand for the compliance-operator." \
        io.openshift.tags="openshift,compliance,security" \
        com.redhat.delivery.appregistry="false" \
        summary="OpenSCAP scanner for compliance-operator" \
        description="An OpenSCAP operand for the compliance-operator" \
        maintainer="Red Hat ISC <isc-team@redhat.com>" \
        License="GPLv2+" \
        name="compliance/openshift-compliance-openscap-rhel8" \
        cpe="cpe:/a:redhat:openshift_compliance_operator:1::el9" \
        com.redhat.component="openshift-compliance-openscap-container" \
        io.openshift.maintainer.product="OpenShift Container Platform" \
        io.openshift.maintainer.component="Compliance Operator" \
        run="podman run --privileged -v /:/host  -eHOSTROOT=/host -ePROFILE=xccdf_org.ssgproject.content_profile_coreos-fedramp -eCONTENT=ssg-rhcos4-ds.xml -eREPORT_DIR=/reports -eRULE=xccdf_org.ssgproject.content_rule_selinux_state" \
        version=1.8.0-dev

RUN microdnf -y update glibc
RUN microdnf -y install openscap openscap-scanner
RUN microdnf clean all

COPY ./LICENSE /licenses/LICENSE
