#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/coverage.sh"

TEST_OUTPUT="${1:?Usage: $0 <test-output-log> <output-baseline>}"
OUTPUT="${2:?Usage: $0 <test-output-log> <output-baseline>}"

if [ ! -f "$TEST_OUTPUT" ]; then
    echo "ERROR: Test output $TEST_OUTPUT not found."
    exit 1
fi

{
    echo "# Coverage baseline for compliance-operator"
    echo "# Generated by: make update-coverage-baseline"
    echo "# Do not edit manually."
    extract_coverage "$TEST_OUTPUT" | sort
} > "$OUTPUT"

echo "Coverage baseline written to $OUTPUT:"
cat "$OUTPUT"
