name: Release latest

on:
  push:
    branches: ["master"]

jobs:
  # Build bundle with Quay.io Konflux image references
  # Operator, openscap, content, and must-gather images are built by Konflux
  bundle-container-push-latest:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-bundle
      registry_org: complianceascode
      tag: latest
      dockerfile_path: bundle.Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x,linux/arm64"

  catalog-container-push-pr:
    needs:
      - bundle-container-push-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-catalog
      registry_org: complianceascode
      tag: latest
      dockerfile_path: catalog.Dockerfile
      vendor: "Compliance Operator Authors"
      prepare_command: |
        make catalog-docker BUNDLE_IMGS=ghcr.io/complianceascode/compliance-operator-bundle:latest
      platforms: "linux/amd64,linux/ppc64le,linux/s390x,linux/arm64"
